[package]
name = "zinder-wallet-rocksdb"
version = "0.1.0"
description = "Version-1 RocksDB wallet projection storage and construction"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "wallet"]
categories = ["database"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rust-rocksdb.workspace = true
thiserror.workspace = true
zinder-core.workspace = true
zinder-bulk-load.workspace = true
zinder-store.workspace = true
zinder-wallet-projection.workspace = true

[dev-dependencies]
prost.workspace = true
tempfile.workspace = true
zinder-proto.workspace = true

[lints]
workspace = true
