[package]
name = "zinder-proto"
version.workspace = true
description = "Zinder-owned generated protocol modules"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "protocol"]
categories = ["network-programming"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tonic-types.workspace = true
thiserror.workspace = true
zinder-core = { path = "../zinder-core", default-features = false }

[package.metadata.cargo-machete]
# The generated modules included from OUT_DIR reference these crates directly.
ignored = ["prost", "tonic", "tonic-prost"]

[build-dependencies]
prost-build.workspace = true
tonic-prost-build.workspace = true

[dev-dependencies]
eyre.workspace = true
prost-types.workspace = true

[lints]
workspace = true
