[package]
name = "zinder-core"
version.workspace = true
description = "Core Zinder chain epoch and artifact domain values"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "zinder"]
categories = ["database"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = ["commitment-tree-codec"]
commitment-tree-codec = [
    "dep:incrementalmerkletree",
    "dep:orchard",
    "dep:sapling",
    "dep:zcash_primitives",
]

[dependencies]
blake2b_simd.workspace = true
hex.workspace = true
incrementalmerkletree = { version = "0.8.2", features = ["legacy-api"], optional = true }
orchard = { version = "0.15.0", default-features = false, optional = true }
prost.workspace = true
sapling = { package = "sapling-crypto", version = "0.7.0", default-features = false, optional = true }
sha2.workspace = true
thiserror.workspace = true
zcash_primitives = { version = "0.29.0", default-features = false, features = ["std"], optional = true }
zcash_address = { version = "0.13.0", default-features = false, features = ["std"] }
zcash_protocol = { version = "0.10.0", default-features = false, features = ["std"] }

[dev-dependencies]
eyre.workspace = true

[lints]
workspace = true
