[package]
name = "zinder-core"
version = "0.1.0"
description = "Core Zinder chain epoch and artifact domain values"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "zinder"]
categories = ["database"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blake2b_simd.workspace = true
hex.workspace = true
sha2.workspace = true
thiserror.workspace = true
zcash_address = { version = "0.13.0-pre.0", default-features = false, features = ["std"] }
zcash_protocol = { version = "0.10.0-pre.0", default-features = false, features = ["std"] }

[dev-dependencies]
eyre.workspace = true

[lints]
workspace = true
