[package]
name = "zinder-core"
version.workspace = true
description = "Core Zinder chain epoch and artifact domain values"
edition.workspace = true
readme = "README.md"
keywords = ["zcash", "indexer", "zinder"]
categories = ["database"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
include = [
    "/src/**",
    "/Cargo.toml",
    "/README.md",
]

[features]
default = ["commitment-tree-codec"]
commitment-tree-codec = [
    "dep:incrementalmerkletree",
    "dep:orchard",
    "dep:sapling",
    "dep:zcash_primitives",
]

[dependencies]
blake2b_simd.workspace = true
hex.workspace = true
incrementalmerkletree = { workspace = true, features = ["legacy-api"], optional = true }
orchard = { workspace = true, default-features = false, optional = true }
prost.workspace = true
sapling = { workspace = true, optional = true }
sha2.workspace = true
thiserror.workspace = true
zcash_primitives = { workspace = true, features = ["std"], optional = true }
zcash_address = { workspace = true, features = ["std"] }
zcash_protocol = { workspace = true, features = ["std"] }

[dev-dependencies]
eyre.workspace = true

[lints]
workspace = true
