[package]
name = "zinder-client-local"
version.workspace = true
description = "Private colocated storage adapter for zinder-client"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
remote-fallback = ["zinder-client/remote"]

[dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zinder-client = { path = "../zinder-client", default-features = false }
zinder-core = { path = "../zinder-core", default-features = false }
zinder-materialized-views.workspace = true
zinder-store.workspace = true

[dev-dependencies]
eyre.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tonic = { workspace = true, features = ["server", "transport"] }
zinder-proto.workspace = true
zinder-query.workspace = true
zinder-testkit.workspace = true

[[test]]
name = "acceptance"
path = "tests/acceptance.rs"

[[test]]
name = "parity-acceptance"
path = "tests/parity_acceptance.rs"
required-features = ["remote-fallback"]

[lints]
workspace = true
