[package]
name = "zinder-wallet-projection"
version = "0.1.0"
description = "Wallet projection domain and durable encoding contracts"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "wallet"]
categories = ["database"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blake2b_simd.workspace = true
thiserror.workspace = true
zinder-core.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
