[package]
name = "zinder-testkit"
version.workspace = true
description = "Deterministic chain, store, and node fixtures for Zinder tests"
edition.workspace = true
readme = "../../README.md"
keywords = ["zcash", "indexer", "testkit", "fixtures"]
categories = ["development-tools::testing"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
color-eyre.workspace = true
eyre.workspace = true
incrementalmerkletree = { workspace = true, features = ["legacy-api"] }
orchard.workspace = true
parking_lot.workspace = true
rand = "0.8"
serde_json.workspace = true
secp256k1 = { workspace = true, default-features = false, features = ["alloc"] }
sapling.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["process", "sync"] }
tokio-stream.workspace = true
tokio-util.workspace = true
tonic = { workspace = true, features = ["server", "transport"] }
tracing.workspace = true
tracing-subscriber.workspace = true
zcash_address = { workspace = true, features = ["std"] }
zcash_primitives = { workspace = true, features = ["circuits", "transparent-inputs", "std", "test-dependencies"] }
zcash_protocol = { workspace = true, features = ["local-consensus", "std"] }
zcash_transparent = { workspace = true, features = ["transparent-inputs", "std"] }
zinder-core.workspace = true
zinder-materialized-views.workspace = true
zinder-proto.workspace = true
zinder-source.workspace = true
zinder-store.workspace = true
zinder-wallet-rocksdb.workspace = true
zip32.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-stream.workspace = true

[lints]
workspace = true
